### ISSUE TITLE
Don't work on Win 11

### ISSUE THREAD

**Issue by maxrave-dev** [cherryleafroad/flp-plugins#1]

**Comment by MolotovCherry** [comment]
Need more details. What's broken? What happens? How to reproduce it?

I'm on Win11 and it works fine for me
![image](https://user-images.githubusercontent.com/13651622/204587256-8aacc16a-dba2-4094-bd47-2234e5360b2b.png)

**Comment by maxrave-dev** [comment]
https://user-images.githubusercontent.com/113747128/204763711-e9c61142-42a7-4e3a-8e34-4b9e3f01b048.mp4

it dont open :((((
i try to open with administrator permission but still dont work

**Comment by MolotovCherry** [comment]
It's a command line app. Open a cmd or PowerShell window first, then execute the program (I put some instructions on the main page)

(You don't need admin permissions)

**Comment by maxrave-dev** [comment]
Oh it worked. Thank you very much for your work ❤️❤️❤️
